# Generated by Django 6.0.5 on 2026-08-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_bairro_usuario_cep_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='capa',
            field=models.ImageField(upload_to='media/planos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/perfis/'),
        ),
    ]
