# Generated by Django 6.0.5 on 2026-08-31 04:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_plano_capa_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, default='static/planos/default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
