# Generated by Django 6.0.5 on 2026-08-31 15:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_plano_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, default='perfis/default05', max_length=255, null=True, verbose_name='image'),
        ),
    ]
