# Generated by Django 6.0.5 on 2026-09-28 17:09

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_plano_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('capa', cloudinary.models.CloudinaryField(blank=True, default='default', max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='plano',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='app.servicos'),
            preserve_default=False,
        ),
    ]
