# Generated by Django 6.0.5 on 2026-09-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_servicos_plano_servico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
    ]
