# Generated by Django 6.0.5 on 2026-09-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_servicos_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ordem',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
